# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: test-normal
      run: |
          myDirectories=("account" "erratum", "grade_school", "queen_attack")
      
          for i in "${myDirectories[@]}"
          do
            cd $i
            #go build
            go test
            cd ..
          done
          
    - name: test-benchmark
      run: |
          myDirectories=("parallel_letter_frequency" )
      
          for i in "${myDirectories[@]}"
          do
            cd $i
            #go build
            go test -bench .
            cd ..
          done

    #- name: Build
    #  run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
